### ISSUE TITLE
SSH Support Broken

### ISSUE THREAD

**Issue by NTICompass** [keepkey/keepkey-firmware#51]
SSH support on the KeepKey was fixed in firmware 5.4.1 (I've been on the rc version), but now on the latest (5.6.1) and the new bootloader, SSH is no longer working.

In Linux, I am seeing the following with `keepkey-agent`:

```
Traceback (most recent call last):
  File "/home/nticompass/.local/lib64/python3.5/site-packages/libagent/device/trezor.py", line 151, in sign
    ecdsa_curve_name=curve_name)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 135, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 690, in sign_identity
    return self.call(proto.SignIdentity(identity=identity, challenge_hidden=challenge_hidden, challenge_visual=challenge_visual, ecdsa_curve_name=ecdsa_curve_name))
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 148, in wrapped_f
    return f(*args, **kwargs)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 189, in call
    msg = handler(resp)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 201, in callback_Failure
    raise CallException(msg.code, msg.message)
keepkeylib.client.CallException: (1, 'Unknown message')
```

In Windows, under TrezorSSHAgent.exe:

```
[18.07.2018 23:00:59] SEVERE: Sign operation failed
com.trezoragent.exception.SignFailedException: Sign operation failed on HW.
	at com.trezoragent.sshagent.DeviceWrapper.signChallenge(DeviceWrapper.java:123)
	at com.trezoragent.sshagent.SSHAgent.processSignRequest(SSHAgent.java:253)
	at com.trezoragent.sshagent.SSHAgent.answerMessage(SSHAgent.java:170)
	at com.trezoragent.sshagent.SSHAgent.answerIfDevicePresent(SSHAgent.java:224)
	at com.trezoragent.sshagent.SSHAgent.processMessage(SSHAgent.java:149)
	at com.trezoragent.sshagent.SSHAgent.callback(SSHAgent.java:111)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:485)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:515)
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:390)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at com.sun.proxy.$Proxy0.GetMessage(Unknown Source)
	at com.trezoragent.sshagent.SSHAgent.startMainLoop(SSHAgent.java:96)
	at com.trezoragent.gui.TrayProcess.start(TrayProcess.java:96)
	at com.trezoragent.gui.StartAgentGUI.main(StartAgentGUI.java:50)
```

**Comment by NTICompass** [comment]
@keepkeyjon It looks like SSH support didn't make its way into the new cmake version of the firmware.  Can this be added back?  I've been using the KeepKey to SSH into things :-)

**Comment by keepkeyjon** [comment]
Oops. We should have that fixed in the next firmware release.

**Comment by keepkeyjon** [comment]
[v5.7.0](https://github.com/keepkey/keepkey-firmware/releases/tag/v5.7.0), which is currently released in the [beta client](https://chrome.google.com/webstore/detail/keepkey-client-rc/ndpjhnboalogfiafbknodggihfiedibo) should fix this. Please let me know if you're still having issues with it.

**Comment by NTICompass** [comment]
@keepkeyjon I updated to v5.7.0 and SSH is working again!  Thanks a lot, man :-)
